### PR TITLE
Refactoring geolocation to mirror Locast methods.

### PR DESCRIPTION
**Pull request by FozzieBear**
Throwing this out as a proposal to update how the geolocation is performed (after geojs.io suddenly started placing me on the other side of the country by IP, ha). I poked around a bit at how locast.org does geolocation when not available via browser, and this is about as close as I could get. It transitions away from using a manual lat\lon to override an incorrect location, and uses zipcode instead. Also adds in a check via the 'active' value returned from the Locast API, to abort and provide a user friendly error if Locast reports service isn't available in the area. 

Changes:
- Update geolocation methods to try and mirror how locast.org/dma operates.
- Instead of overridding via lat\long, resolve location via more user friendly zipcode. 
- Also allows for a check if Locast has active service in the area and provides a more descriptive error if not.
- Refactored the exception logic for calling urls into a decorator to allow the removal of some duplicate code blocks. 
- Give donation expiration in human readable format instead of epoch.

### CODE REVIEW

**Comment by tgorgdotcom** [comment]
I think this is good, except for one minor change.  If we could support both `override_longitude` and `override_latitude` and the new `override_zipcode`, that would be great.  Mainly to try to do better with breaking changes.

**Comment by FozzieBear** [comment]
Sure, that's easy enough. I'll knock something together later tonight.

**Comment by FozzieBear** [comment]
Updated to accommodate the current `override_longitude` and `override_latitude` configuration options. If both coords and a new `override_zipcode` parameter were provided, the coords currently take precedence.

**Comment by tgorgdotcom** [comment]
Just did some testing on this on my end.  For some reason the Locast's geo IP pins me to Washington DC, even though I'm in PA (even on their website).  I was thinking about reverting just the GeoIP part, but I know that's not working for you.  Not sure what we would do to make it more accurate for both of our locations...

**Comment by FozzieBear** [comment]
Yeah, geolocation via IP is inherently...messy...at best. With a truckload of different vendors all providing their own databases, it's a crapshoot as to who's gonna have the right information for any one particular address. I figured using the Locast service (and therefore whoever they're using in the background for their IP > location lookups) was as good as any for a 'source of truth'. Without access to the relative precision of the in browser geolocation API, picking an IP>location service and providing a couple good override options is probably about as good as we can get.

When checking via the browser, is that using the browser location, or "IP" tab in the upper right? If we're getting a different location via the IP on that tab vs in the script, that's def odd.

**Pull request merged**
