### PR TITLE
Massive OverHaul

### PR DESCRIPTION
**Pull request by deathbybandaid**
Going to preface this with, I had a full free day, and I chose to play with locast2plex.

This contains multiple PRs worth of changes, with a single end result that I was striving for, translating the Locast EPG to xmltv format.

I've been testing and running this for about a day now (as of writing). I am marking this as a Draft PR, as it is mostly where I see this codebase needing to go.

What this PR does (list):

* Seperate core functionality of the script, cleaning `main.py` and splitting into multiple files.
* Create a new Class for config handling.
* Make Config more usable throughout the script.
* Seperate Config options into a few sections. `locast2plex` for things directly related with running this script, `locast` for things directly related to connecting to locast, and `dev` for options that most people won't need to touch.
* Seperate the Location finding, and move it earlier in the script, to be used in more than one facet.
* Location information is now a `dict` and very simple to use.
* Create a shared `L2PTools.py` file to host functions that multiple scripts might need.
* Create a `data` directory to house some of the loose non-script files.
* Clean up loose JSON files into new `data` directory
* Update Dockerfile to COPY the new `data` directory, instead of just the loose JSON files.
* Generate a dummy XML file while we pull the data from Locast.
* Pulls EPG data from Locast with a configurable option for how often. This will cache 7 days worth into the new `data/cache` directory.
* Host new `/xmltv.xml` file for use by Plex/Emby/Jellyfin.
* Update DMA listing to include ALL of the locations.
* Made External IP display correctly in console output.
* Get the script directory and use the full path for file access, instead of changing the directory in `main.py`.
* Cleaned up the termination of a stream, so we don't get a `ValueError` for ffmpeg.

### CODE REVIEW

**Comment by deathbybandaid** [comment]
Added a count of channels to things this does

**Comment by deathbybandaid** [comment]
The DMA listing I had found in #75 Had some duplicate entries for DMA. Originally, my thought was to dedupe, however, the alternative city names associated with a DMA could potentially prove useful.

I intentionally used `raise ValueError` in testing, and was able to correctly get the channel numbers for DMA 501.

**Comment by deathbybandaid** [comment]
My next step is to have a scheduled task to pull and update the FCC facility list, but only if the online file is newer

**Comment by deathbybandaid** [comment]
Okay, so these newer pushes do some more stuff, like a scheduled FCC Facility Database update, and then cached.

Unfortunately, in my testing I had to `nano /etc/ssl/openssl.cnf` and comment out `#CipherString = DEFAULT@SECLEVEL=2` to download the FCC database.

I've also moved the ffmpeg executable, and made a configuration option for specifying ffmpeg path. For Windows (now detected), we'll be able to just use the new ffmpeg path.

I've moved some of the random files to `data/other`.

**Comment by deathbybandaid** [comment]
@tgorgdotcom I'm betting you've been busy, but you want to glance at this and see if you like what I've done?

**Comment by deathbybandaid** [comment]
I know #70 was closed, but I've added a dev setting to adjust the tuner type.

To clarify, `[dev]` settings are things the average user should not need to adjust. Additionally, some options such as `tuner_type` are there for testing purposes, and should not be officially supported.

However, I'd say if enough testing of a dev setting is done, maybe we "promote" a setting to `[locast]`

**Comment by deathbybandaid** [comment]
I did a test with `tuner_type` set to `Cable`, and plex had a heart attack. I'm betting that this setting would need to correspond with the hdhr hardware that we claim to be.

**Comment by deathbybandaid** [comment]
It looks like dizquetv claims to be a `Cable` device

````
"ModelNumber":"HDTC-2US"
"FirmwareName":"hdhomeruntc_atsc"
"FirmwareVersion":"20170930"
````

Maybe tomorrow, I'll check if switching to that makes it work as `cable`

**Comment by deathbybandaid** [comment]
Okay, so I had a second of freetime tonight, and adjusting the tuner type to `Cable` worked, with the appropriate HDHR settings

**Comment by deathbybandaid** [comment]
More configuration changes, looking at doing some different things with ffmpeg specifically

**Comment by deathbybandaid** [comment]
Latest Pull is a HUGE improvement. Using the headers for GET requests, we can now determine the actual `base_url` that locast2plex was accessed. this makes setting the `listen_address` to 0.0.0.0 far more effective for non-docker users.

**Comment by deathbybandaid** [comment]
This last push adds a `--config_file` CLI argument, and a `cache_dir` configuration option.

This allows us to specify a config file outside of the `script_dir` as well as the cache for facilities and EPG information

**Comment by deathbybandaid** [comment]
Considering there are only 2 other PRs open, if this branch was tested, I'd say it's ready to be merged. I'll hold off on coding anything further until I hear something.

**Comment by jcastilloalonso** [comment]
> 
> 
> Okay, so I had a second of freetime tonight, and adjusting the tuner type to `Cable` worked, with the appropriate HDHR settings

Any reason for preferring Cable over Air? I would guess is for pushing EPG data to Plex. Is there any reason why this is better? I've been using Plex data directly without problem, just curious on why one would be better than the other.

**Comment by deathbybandaid** [comment]
> > Okay, so I had a second of freetime tonight, and adjusting the tuner type to `Cable` worked, with the appropriate HDHR settings
> 
> Any reason for preferring Cable over Air? I would guess is for pushing EPG data to Plex. Is there any reason why this is better? I've been using Plex data directly without problem, just curious on why one would be better than the other.

If people are combining their Local Antenna/Cable with Locast2Plex, it may be important for this to be set the same.

**Comment by tgorgdotcom** [comment]
Just a few things to point out:

- Could we, for the time being, keep most of the options in `[main]`?   The new options can be split out, if you'd like.  I think the principle of what you did is important, and we can re-organize everything starting with 2.x-alpha release.

- Pulling FCC records periodicially - not a bad idea, just make sure the data file exists and is not blank, as the download from the FCC will sometimes return.  Also, the FCC updates the db from 4:00 AM and 5:00 AM ET, and they advise not to download during that time.

- fcc_dma_markets: make sure this is mapping to the correct "nielsen_dma" value in tv_stations.json

**Comment by deathbybandaid** [comment]
I'll leave this PR open for anybody that wants to pick it apart for ideas.

I've since moved on to a complete rewrite in a separate repository. My rewrite (when published) is a system that can be used for various streaming sources, with easily duplicatable code.

My new repository will give credit to this and one other repository for inspiration.

**Comment by deathbybandaid** [comment]
@tgorgdotcom I just want to clarify, I really liked locast2plex, but I code for a few other projects as well, and I'm accustomed to a faster paced code review process, and this PR is an example of how elbow-deep I managed to get without trying.

As stated above, I have taken some code from here, and some code from TVHproxy/npvrProxy, as well as many hours of coding on my own to form something else. In reality, my interest in this project was to be able to fork it into other video streaming abilities.

I am NOT discouraging you from continuing the way you have been, I just was starting to see a trend of differing opinions regarding the future of this specific project.

Another thing that offput me about locast2plex is fairly trivial, having the name "Plex" stamped on the title, as well as a couple `class`s in the code. This works great on anything that could pull signal from an HDHR device, as well as VLC media Player.

If you are curious, I've made a github organization for my new fake HDHR repos (Including one that handles Locast). I Intend to give credit where it is deserved for the inspiration sources.

https://github.com/FAKEHDHR/

**Comment by tgorgdotcom** [comment]
Hello @deathbybandaid, thanks for your reply.  No worries on forking or anything (who knows, maybe I'll end up being a contributor to your project in the future).  As long as what I am doing is helpful to somebody, whether directly or indirectly, then that's great.  Thank you for your contributions and I wish you the best of luck.

**Pull request closed without merging**
