### PR TITLE
Migrate away from Python2

### PR DESCRIPTION
**Pull request by deathbybandaid**
Co-authored-by: ratherDashing

### CODE REVIEW

**Comment by deathbybandaid** [comment]
There were a couple issues with @ratherDashing approach to his PR in #76 
Mostly involving the PR branch now being an outdated 'master'. This PR supersedes that PR, but all credit goes to @ratherDashing for the legwork here.

This PR has been through some light testing, but looks ready to go. The migration from Py2 to Py3 needs to happen before I can start working on several other ideas I have for PRs.

Note:
* I am not a Docker user, so hopefully, I did the Dockerfile correctly.

**Comment by deathbybandaid** [comment]
@tgorgdotcom not trying to rush you, but this repo has really peaked my interest, and I have some ideas that I've already coded, and am running locally. All my code assumes Py3, so those PRs won't hit until this gets merged.

**Comment by tgorgdotcom** [comment]
Sorry for the delay.  I was trying to find a way to give @ratherDashing some credit for the submitted code for tracking purposes.   Everything is good now and I merged your code in.  This is really great!

I think I'm going to switch Docker images so we can get multiplatform working.  I'll put in a code change soon to get that going.

**Comment by ratherDashing** [comment]
@tgorgdotcom @deathbybandaid no need for credit, i'm just happy to help.  you guys are doing all the hard work.  thank you!

**Comment by jcastilloalonso** [comment]
@tgorgdotcom @deathbybandaid and @ratherDashing , Thanks a lot for all the work and effort! Love how amazing community is working on making this better everyday!

**Pull request merged**
