### PR TITLE
Lint Python files in repository.

### PR DESCRIPTION
**Pull request by deathbybandaid**
I was looking at maybe doing some PRs for this project, but couldn't look past the linting issues shown in my editor.

Pending tests, this would be a good one to get merged sooner than later.

### CODE REVIEW

**Comment by deathbybandaid** [comment]
Once this is merged, I'd like to start working on updating this to Python3. Python2 is dead.

A decision needs to also be made at this point in the project to abandon Python2 now, coding backwards compatibility would be a waste of time.

**Comment by tgorgdotcom** [comment]
I like the idea on moving to Python 3, not sure if there may be some trickiness with some of the third party stuff (SSDPServer and m3u8).  But yeah that would be awesome, and I'm definitely up for learning and understanding P3 differences.

As for the linter changes, there seems to be some lines removed for stylistic reasons (i.e. the extra newlines around functions and extra pound signs in specific comments), that I would normally use to make things easier to read for myself.  Just curious, what linter are you using?   Now might be good to discuss coding style as well.  There will be a bit for me to learn as I'm relatively new to Python.

**Comment by deathbybandaid** [comment]
I too used to use additional whitespace for stylistic reasons, but it's easier for collaboration on projects if we try to follow as many of the "rules" as possible. 

I personally use Atom with Pylama installed. I have enabled `pep8` and `pyflakes` which are pretty standard rules.
The ignores I use for all code are `E501,W504,W605`

I did need to add `# pylama:ignore=E722` to the top of two files for using `except:` instead of `except Exception as e:`
This was my choice for this PR to not start modifying actual code yet.

The below image shows a glimpse of what the repo looks like in my editor

image

**Comment by ratherDashing** [comment]
I too am not a Python programmer (Java by trade) but here's my first stab at a P3 migration if we want to do that before linting.

https://github.com/tgorgdotcom/locast2plex/pull/76

**Comment by deathbybandaid** [comment]
I write python for a few other projects. I'd like to see this linting implemented prior to anything that changes the codebase.

**Comment by tgorgdotcom** [comment]
Hello.  Sorry for not getting back to you earlier.  I did some research to more fully understand linting rules in Python (I'm currently working on getting pylama to work in vscode).  I'm okay with most of the changes, except for the spacing rules (E303).  I'll probably end up replacing the extra hash symbols for something else to appease E266.  If you can update your pull without the spacing changes I'll pull it in.  By the way, thanks for all your help -- definitely learning something new through this.

**Comment by deathbybandaid** [comment]
Oof,,, idk if I can mentally handle the spacing around functions not being right

**Comment by deathbybandaid** [comment]
If the py3 PR gets merged first, I can more easily reads the spaces.

I'll `-D` my branch, fetch origin master, remake my branch, and force push with E303 ignored

**Comment by deathbybandaid** [comment]
Looks like a couple other PRs got merged. ,I'll rebase from master, ignore the spacing and relint.

The py3 PR could then be merged AFTER this.

**Comment by deathbybandaid** [comment]
Okay @tgorgdotcom this is ready to be merged, with all the spacing issues ignored.

Honestly doesn't quite feel right leaving all that padding in there, but at least my editor isn't freaking out with the ignore line in there.

I'd like to see this one merged ASAP, and then I have some other PR's that I'd like to do based on a clean repo.

I'll probably revisit the spacing stuff with you at a later point in time.

The python3 PR will need to be rewritten based on the other PRs that were merged, and based on a branch that isn't @ratherDashing 's master branch.

**Comment by tgorgdotcom** [comment]
Thanks for your help.  We can definitely discuss the spacing further.  I finally got the linting process running on my end as well, so I'm hoping to get more experience/understanding with it.

**Pull request merged**
